### ISSUE TITLE
[PACMAN-X] Lecture 01

### ISSUE THREAD

**Issue by DevKang** [DevKang/flutter-study#8]
완료 후 #2 에 PR 남겨주세요

**Comment by PACMAN-X** [comment]
관련 내용 Notion에 학습하여 남깁니다.
중간중간 비어 있는 개념들이 있긴 하지만 계속 듣다보면 해결될 거라는 막연한 믿음을 가지며... 갑니다.
https://www.notion.so/pacmanx/Course-1-c2b9ded004de491aa50f1d07503f593f

**Comment by PACMAN-X** [comment]
관련 내용 Notion에 학습하여 남깁니다.
중간중간 비어 있는 개념들이 있긴 하지만 계속 듣다보면 해결될 거라는 막연한 믿음을 가지며... 갑니다.
https://www.notion.so/pacmanx/Course-1-c2b9ded004de491aa50f1d07503f593f
